[build]
  publish = "_site"
  command = "npm run build-production"

[[plugins]]
package = "./plugins/keep-data-cache"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://zealous-lovelace-73ddf1.netlify.app"
  to = "https://design2seo.com/leaderboards/"
  status = 301
  force = true
